name: SimpleRegionMarket
version: ${majorversion}-${state}
author: theZorro266
main: com.thezorro266.simpleregionmarket.SimpleRegionMarket
depend: ['WorldGuard']
softdepend: ['Vault']

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket limits | list | version

permissions:
  simpleregionmarket.admin:
    description: Admin permissions
